export const partnersData = [{srcLogo: '/l1.png',
  srcProduct: '/p1.png',
  title: 'Macdon M155 | Self-propelled mower',
  description: 'In keeping with MacDon’s tradition of pioneering new technologies, our self-propelled mowers will give you the highest performance in your conditions simply by choosing the right header: draper, rotary disc or auger. With patented Dual Direction® technology, the mower can move across the field at speeds up to 26 km/h and on the road at speeds up to 37 km/h. The comfort and reliability of the machine will allow the operator to mow all day, year after year.',
},
{srcLogo: '/l2.png',
  srcProduct: '/p2.png',
  title: 'JOSKIN | Multifunctional trailers',
  description: 'FOUNDED IN 1968, JOSKIN is a family-owned company that has become a LEADER in the production of agricultural machinery. The company’s factories, located in Belgium, France and Poland with a total indoor area of ​​150,000 m², manufacture and export JOSKIN products to 60 countries. We use the most MODERN HIGH-PRECISION EQUIPMENT: dynamic modeling in three dimensions, laser cutting platforms, bending presses, galvanizing shop.',
},
{srcLogo: '/l3.png',
  srcProduct: '/p3.png',
  title: 'Stationary and mobile pivot irrigation systems',
  description: 'Irrigation (irrigation melioration) is used to increase water reserves in the upper soil layer in order to improve its fertility. Irrigation is carried out by spraying moisture over the surface of the earth and plants using special sprinkler units capable of spraying water as raindrops (hence the name «rainformers»). These units produce artificial rain clouds and supply water to the irrigated area in the form of a «train».',
},
{srcLogo: '/l4.png',
  srcProduct: '/p4.png',
  title: 'Convey-All CST-1550',
  description: 'Convey-All CST-1550 is a rugged 15-inch diameter grain conveyor designed for high-capacity handling in demanding agricultural conditions. Featuring a heavy-duty steel frame and 50-foot maximum length, it delivers up to 5,000 BPH transfer rates with minimal grain damage. The self-tracking belt and enclosed design prevent spillage while ensuring smooth operation. Powered by a hydraulic motor (or optional electric drive), it offers flexible mounting for trucks, bins, or processing lines. Corrosion-resistant components and easy maintenance make it ideal for grain, seed, and fertilizer applications. Built for durability and efficiency, this conveyor maximizes productivity in farm and commercial operations.',
},
{srcLogo: '/l5.png',
  srcProduct: '/p5.png',
  title: 'Fleetguard filters – reliable and efficient cleaning in any conditions',
  description: 'The Fleetguard brand has been one of the most popular brands of purifiers worldwide for many years. The products of this manufacturer have achieved great success in the market due to the high quality and efficiency of cleaning that they provide. In many respects and characteristics, Fleetguard filters are among the best in the world. In addition, the company is constantly working on creating new technologies and developments, which allows it to reach new heights of quality.',
},
{srcLogo: '/l6.png',
  srcProduct: '/p6.png',
  title: 'X15 Performance Series (2021)',
  description: 'A refreshed X15 Performance Series is new to 2021 and designed to meet EPA and Greenhouse Gas Phase 2 requirements. While the X15 Performance Series is being updated from the 2017 version, many hardware changes have been in production since 2020 with the X15 Efficiency Series. Built with Uptime, improved Total Cost of Ownership and Ease of Operations in mind, the 2021 X15 Performance Series is the first choice for drivers that need the power to perform. The 2021 X15 Performance Series incorporated key product improvements launched with the 2020 X15 Efficiency Series and builds off the most successful product launch in Cummins history. With the best “Percent Zero Touch” and lowest “Touches Per Thousand” metrics to date, Cummins expects the trend to continue with the 2021 X15 product lineup.',
},
{srcLogo: '/l7.png',
  srcProduct: '/p7.png',
  title: 'Box type seeder BD7410',
  description: 'Precision seeding is at the core of the BD7410 planter’s design. It features advanced seed counters and a soil drive transmission inherited from its predecessor, the BD7600 series, ensuring precise placement of each seed. This precise control over seeding is essential for achieving optimum emergence and, ultimately, higher yields. Understanding the challenges of modern agriculture, the BD7410 planter has been designed to provide versatility in a variety of soil conditions and crop types. Its adjustable settings allow farmers to tailor their seeding approach to specific field requirements, promoting better crop management and resource utilization.',
},
{srcLogo: '/l8.png',
  srcProduct: '/p8.png',
  title: 'Nardi Pegaso MZH AVANT R8070',
  description: 'Nardi Pegaso MZH AVANT R8070 Header is a high-performance grain and small-seed crop header with a 7-meter working width. It features an auger reel with hydraulic speed and tilt adjustment, along with a reinforced cutting system for efficient harvesting even in lodged crops. Compatible with most combine harvesters thanks to its universal mounting system and hydraulic drives, it ensures seamless integration. The robust steel construction and optimal weight distribution provide stability and durability under heavy-duty conditions. Optional features include automatic terrain-following system and protective covers for enhanced safety. An ideal choice for farmers seeking reliability and high productivity in field harvesting operations.',
},
{srcLogo: '/l9.png',
  srcProduct: '/p9.png',
  title: 'DELTATRACK MODELS 530-620',
  description: 'The Versatile DeltaTrack continues to be a class leader in the market. The 530, 580 and 620 models are never short on power and combine the knowledge and expertise of Versatile engineers with several key industry partners like Cummins, Cat® and Camso. Featuring the largest cab in the segment, the most advanced undercarriage in the industry and convenient serviceability, the DeltaTrack is the perfect combination of power, comfort and reliability.',
},
{srcLogo: '/l10.png',
  srcProduct: '/p10.png',
  title: 'Grain storage for cereals Meridian Mfg',
  description: 'Meridian Mfg Grain Storage for Cereals is a reliable and high-capacity grain storage solution designed for optimal preservation of cereal crops. Constructed from galvanized steel with anti-corrosion coating, it ensures long-term durability. The modular design allows for flexible expansion, with storage capacity ranging from 1,000 to 20,000 tons depending on the model. Equipped with an automated ventilation system and humidity control, it maintains ideal storage conditions while ensuring airtight protection against moisture and pests. Quick assembly on a prepared foundation minimizes setup time, and integrated temperature sensors with real-time monitoring provide enhanced grain management. Ideal for both small farms and large agribusinesses, Meridian Mfg grain storage delivers efficiency, security, and scalability for modern agricultural needs.',
},
{srcLogo: '/l11.png',
  srcProduct: '/p11.png',
  title: 'SUMMERS MFG ULTIMATE NT',
  description: 'The Summers MFG Ultimate NT is a versatile sprayer from Summers with full hydraulic boom control. The electro-hydraulic control system allows the operator to fold the booms into the field position and into the transport position, adjust the boom height on the go or raise the end sections to overcome obstacles without leaving the tractor cab. The robust frame is made from 10 x 20 cm (4 x 8 inch) square steel tubing, with a 3,785 l and 5,678 l tank. Parallel coupling ensures strength when lifting the booms and a constant spray nozzle angle regardless of the field contour. Separate hydraulic end lift cylinders allow the ends of each boom to be raised to overcome obstacles and compensate for curves and uneven terrain.',
},
{srcLogo: '/l12.png',
  srcProduct: '/p12.png',
  title: 'Seeder for No-Till SPECIAL 4 AIR DRILL 8 m.',
  description: 'Direct sowing of all types of seeds with fertilization. For fused surfaces - wheat, barley, soybeans, sorghum, rapeseed. Row spacing of 17.5 cm, 19.1 cm, 21 cm, 26 cm (on request for machine configuration). This model of seeder can be equipped with additional elements for precise sowing of row crops - corn, sunflower, sorghum and others. Row spacing from 38 cm to 70 cm - from 6 to 29 rows.',
},
{srcLogo: '/l13.png',
  srcProduct: '/p13.png',
  title: 'INLINE LANDROLLER MANDAKO',
  description: 'What initially started as a rock roller has evolved into a multi-use and valuable farm asset. Landrollers smooth the field surface by pushing down rocks and debris, allowing the cutter bar to operate effectively and reduce the risk of repairs. Create better germination with optimal soil-to-seed contact. Increase yields on your farm with a Mandako Landroller!',
},


]